

let all_product = [
  {
    id: 1,
    name: "Sectional Sofa",
    category: "living room",
    imageURL:"https://i.postimg.cc/sgMHTbhn/pexels-max-rahubovskiy-7031737.jpg",
    new_price: 50.0,
    old_price: 80.5,
    note: 7,
  },
  {
    id: 2,
    name: "Chesterfield Sofa",
    category: "living room",
    imageURL: "https://i.postimg.cc/rwnpGRk6/London-Legacy-Bike-Tan-6-min.jpg",
    new_price: 85.0,
    old_price: 120.5,
    note: 4,
  },
  {
    id: 3,
    name: "Lawson Sofa",
    category: "living room",
    imageURL: "https://i.postimg.cc/G29GJnNK/pexels-leah-kelley-6480707.jpg",
    new_price: 60.0,
    old_price: 100.5,
    note: 7,
  },
  {
    id: 4,
    name: "Camelback Sofa",
    category: "living room",
    imageURL: "https://i.postimg.cc/4xDC5gB5/camelback-sofa-with-braid-1.jpg",
    new_price: 100.0,
    old_price: 150.0,
    note: 2,
  },
  {
    id: 5,
    name: "Mid-Century Modern Sofa",
    category: "living room",
    imageURL: "https://i.postimg.cc/HLMrZTHs/Scandi-inspired-mid-century.webp",
    new_price: 85.0,
    old_price: 120.5,
    note: 8,
  },
  {
    id: 6,
    name: "Tuxedo Sofa",
    category: "living room",
    imageURL: "https://i.postimg.cc/P5rcQqWY/pexels-ilya-shakir-2440471.jpg",
    new_price: 85.0,
    old_price: 120.5,
    note: 4,
  },
  {
    id: 7,
    name: "Loveseat",
    category: "bed",
    imageURL: "https://i.postimg.cc/X77KqBcM/pexels-ksenia-chernaya-3965534.jpg",
    new_price: 85.0,
    old_price: 120.5,
    note: 5,
  },
  {
    id: 8,
    name: "Sleeper Sofa ",
    category: "bed",
    imageURL: "https://i.postimg.cc/0NpZDRzh/5e0d125c59498ff2caec04284c4453f3.jpg",
    new_price: 85.0,
    old_price: 120.5,
    note: 7,
  },
  {
    id: 9,
    name: "Chaise Lounge",
    category: "sofa",
    imageURL: "https://i.postimg.cc/bYFMzPkR/pexels-max-rahubovskiy-6198655.jpg",
    new_price: 85.0,
    old_price: 120.5,
    note: 8,
  },
  {
    id: 10,
    name: "Reclining Sofa",
    category: "table",
    imageURL: "https://i.postimg.cc/mgFhdTNp/WM325-Divani-2s-T414-IMG3366.webp",
    new_price: 85.0,
    old_price: 120.5,
    note: 2,
  },
  {
    id: 11,
    name: "futon",
    category: "sofa",
    imageURL: "https://i.postimg.cc/44VgFnr9/pexels-andrea-davis-12931939.jpg",
    new_price: 85.0,
    old_price: 120.5,
    note: 2,
  },
  {
    id: 12,
    name: "Settee",
    category: "bookshell",
    imageURL: "https://i.postimg.cc/nch39PYh/pexels-max-rahubovskiy-6969790.jpg",
    new_price: 85.0,
    old_price: 120.5,
    note: 2,
  },
  {
    id: 13,
    name: "divan",
    category: "table",
    imageURL: "https://i.postimg.cc/bvxxBxH5/pexels-max-rahubovskiy-6186821.jpg",
    new_price: 85.0,
    old_price: 120.5,
    note: 8,
  },
  {
    id: 14,
    name: "cabriole sofa",
    category: "sofa",
    imageURL: "https://i.postimg.cc/N0DyXpxQ/86c2780341b609ed84846fb3ef7912cc.jpg",
    new_price: 85.0,
    old_price: 120.5,
    note: 2,
  },
  {
    id: 15,
    name: "English Roll Arm Sofa",
    category: "sofa",
    imageURL: "https://i.postimg.cc/W12JXd1N/pexels-vlada-karpovich-4050345.jpg",
    new_price: 85.0,
    old_price: 120.5,
    note: 2,
  },
  {
    id: 16,
    name: "knole sofa",
    category: "bookshell",
    imageURL: "https://i.postimg.cc/zBDtNz78/pexels-maksim-goncharenok-4352247.jpg",
    new_price: 85.0,
    old_price: 120.5,
    note: 4,
  },
  {
    id: 17,
    name: "Bridgewater Sofa",
    category: "bed",
    imageURL: "https://i.postimg.cc/GmJ6n5RP/pexels-rachel-claire-4857775.jpg",
    new_price: 85.0,
    old_price: 120.5,
    note: 7,
  },
  {
    id: 18,
    name: "Empire Sofa",
    category: "bed",
    imageURL: "https://i.postimg.cc/QtB6C62y/sofa-323c7f-1024.jpg",
    new_price: 85.0,
    old_price: 120.5,
    note: 2,
  },
  {
    id: 19,
    name: "Convertible Sofa ",
    category: "sofa",
    imageURL: "https://i.postimg.cc/9MJWXfjp/I16-TROPECA-528-01.webp",
    new_price: 85.0,
    old_price: 120.5,
    note: 2,
  },
  {
    id: 20,
    name: "canapé sofa",
    category: "bed",
    imageURL: "https://i.postimg.cc/Y0KJHKv3/pexels-max-rahubovskiy-6758245.jpg",
    new_price: 85.0,
    old_price: 120.5,
    note: 2,
  },
];

export default all_product;
